In [55]:
import pandas as pd
df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head(2)

                          question  answer
0   What is the capital of France?   Paris
1  What is the capital of Germany?  Berlin

In [56]:
# Tokenized
def tokenize(text):
  text = text.lower()
  text = text.replace('\n', ' ')
  return text.split()

In [57]:
# Vocab
vocab = {'<LINK>':0}

In [58]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question + tokenized_answer
  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [59]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [60]:
vocab

{'<LINK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france?': 6,
 'paris': 7,
 'germany?': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'?": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system?': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius?': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa?': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64?': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold?': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end?': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'world?': 52,
 'nile': 53,
 'japan?': 54,
 'tokyo': 55,
 'developed': 56,
 'theory': 57,
 'relativity?': 58,
 'albert-einstein': 59,
 'freezing': 60,
 'fahrenheit?': 61,
 '32': 62,
 'known': 63,
 'as': 64,
 'red': 65,
 'planet?': 66,
 'mars': 67,
 'author': 68,
 "'1984'?": 69,
 'george-orwell': 70,
 'currency': 71,
 'united': 72,
 'kingdom?': 73,
 'pound': 74,
 'india?': 75,
 'delhi': 76,
 'discovered': 77,
 'gravity?': 78,
 'newton': 79,
 'how': 80,
 'many': 81,
 'continents': 82,
 'are': 83,
 'there': 84,
 'on': 85,
 'earth?': 86,
 '7': 87,
 'gas': 88,
 'do': 89,
 'plants': 90,
 'use': 91,
 'photosynthesis?': 92,
 'co2': 93,
 'smallest': 94,
 'prime': 95,
 'number?': 96,
 '2': 97,
 'invented': 98,
 'telephone?': 99,
 'alexander-graham-bell': 100,
 'australia?': 101,
 'canberra': 102,
 'ocean': 103,
 'largest?': 104,
 'pacific-ocean': 105,
 'speed': 106,
 'light': 107,
 'vacuum?': 108,
 '299,792,458m/s': 109,
 'language': 110,
 'spoken': 111,
 'brazil?': 112,
 'portuguese': 113,
 'penicillin?': 114,
 'alexander-fleming': 115,
 'canada?': 116,
 'ottawa': 117,
 'mammal': 118,
 'whale': 119,
 'element': 120,
 'has': 121,
 'atomic': 122,
 'number': 123,
 '1?': 124,
 'hydrogen': 125,
 'tallest': 126,
 'mountain': 127,
 'everest': 128,
 'city': 129,
 'big': 130,
 'apple?': 131,
 'newyork': 132,
 'planets': 133,
 "'starry": 134,
 "night'?": 135,
 'vangogh': 136,
 'formula': 137,
 'water?': 138,
 'h2o': 139,
 'italy?': 140,
 'rome': 141,
 'country': 142,
 'famous': 143,
 'sushi?': 144,
 'japan': 145,
 'was': 146,
 'first': 147,
 'person': 148,
 'to': 149,
 'step': 150,
 'moon?': 151,
 'armstrong': 152,
 'main': 153,
 'ingredient': 154,
 'guacamole?': 155,
 'avocado': 156,
 'sides': 157,
 'does': 158,
 'hexagon': 159,
 'have?': 160,
 '6': 161,
 'china?': 162,
 'yuan': 163,
 "'pride": 164,
 'and': 165,
 "prejudice'?": 166,
 'jane-austen': 167,
 'iron?': 168,
 'fe': 169,
 'hardest': 170,
 'natural': 171,
 'substance': 172,
 'diamond': 173,
 'continent': 174,
 'by': 175,
 'area?': 176,
 'asia': 177,
 'president': 178,
 'states?': 179,
 'george-washington': 180,
 'bird': 181,
 'its': 182,
 'ability': 183,
 'mimic': 184,
 'sounds?': 185,
 'parrot': 186,
 'longest-running': 187,
 'animated': 188,
 'tv': 189,
 'show?': 190,
 'simpsons': 191,
 'vaticancity': 192,
 'most': 193,
 'moons?': 194,
 'saturn': 195,
 "'romeo": 196,
 "juliet'?": 197,
 'shakespeare': 198,
 "earth's": 199,
 'atmosphere?': 200,
 'nitrogen': 201,
 'bones': 202,
 'adult': 203,
 'human': 204,
 'body?': 205,
 '206': 206,
 'metal': 207,
 'liquid': 208,
 'at': 209,
 'room': 210,
 'temperature?': 211,
 'mercury': 212,
 'russia?': 213,
 'moscow': 214,
 'electricity?': 215,
 'benjamin-franklin': 216,
 'second-largest': 217,
 'land': 218,
 'canada': 219,
 'color': 220,
 'ripe': 221,
 'banana?': 222,
 'yellow': 223,
 'month': 224,
 '28': 225,
 'days': 226,
 'common': 227,
 'year?': 228,
 'february': 229,
 'study': 230,
 'living': 231,
 'organisms': 232,
 'called?': 233,
 'biology': 234,
 'home': 235,
 'great': 236,
 'wall?': 237,
 'china': 238,
 'bees': 239,
 'collect': 240,
 'from': 241,
 'flowers?': 242,
 'nectar': 243,
 'opposite': 244,
 "'day'?": 245,
 'night': 246,
 'south': 247,
 'korea?': 248,
 'seoul': 249,
 'bulb?': 250,
 'edison': 251,
 'humans': 252,
 'breathe': 253,
 'survival?': 254,
 'oxygen': 255,
 '144?': 256,
 '12': 257,
 'pyramids': 258,
 'giza?': 259,
 'egypt': 260,
 'sea': 261,
 'creature': 262,
 'eight': 263,
 'arms?': 264,
 'octopus': 265,
 'holiday': 266,
 'celebrated': 267,
 'december': 268,
 '25?': 269,
 'christmas': 270,
 'yen': 271,
 'legs': 272,
 'spider': 273,
 'sport': 274,
 'uses': 275,
 'net,': 276,
 'ball,': 277,
 'hoop?': 278,
 'basketball': 279,
 'kangaroos?': 280,
 'australia': 281,
 'female': 282,
 'minister': 283,
 'uk?': 284,
 'margaretthatcher': 285,
 'fastest': 286,
 'animal?': 287,
 'cheetah': 288,
 'periodic': 289,
 'table?': 290,
 'spain?': 291,
 'madrid': 292,
 'closest': 293,
 'sun?': 294,
 'father': 295,
 'computers?': 296,
 'charlesbabbage': 297,
 'mexico?': 298,
 'mexicocity': 299,
 'colors': 300,
 'rainbow?': 301,
 'musical': 302,
 'instrument': 303,
 'black': 304,
 'white': 305,
 'keys?': 306,
 'piano': 307,
 'americas': 308,
 '1492?': 309,
 'christophercolumbus': 310,
 'disney': 311,
 'character': 312,
 'long': 313,
 'nose': 314,
 'grows': 315,
 'it': 316,
 'when': 317,
 'lying?': 318,
 'pinocchio': 319,
 'directed': 320,
 'movie': 321,
 "'titanic'?": 322,
 'jamescameron': 323,
 'superhero': 324,
 'also': 325,
 'dark': 326,
 'knight?': 327,
 'batman': 328,
 'brasilia': 329,
 'fruit': 330,
 'king': 331,
 'fruits?': 332,
 'mango': 333,
 'eiffel': 334,
 'tower?': 335,
 'france': 336}

In [61]:
# convert words to numerical indices
def text_to_indices(text, vocab):
  indexed_text = []
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<LINK>'])
  return indexed_text

In [62]:
text_to_indices('what is campus x', vocab)

[1, 2, 0, 0]

In [63]:
import torch
from torch.utils.data import Dataset, DataLoader

In [64]:
class QADataset(Dataset):
  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [65]:
dataset = QADataset(df, vocab)

In [66]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [86]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[ 42, 224, 121, 225, 226,  19,  14, 227, 228]]) tensor([229])
tensor([[  1,   2,   3,  17, 118,  85,  86]]) tensor([119])
tensor([[ 42, 261, 262, 121, 263, 264]]) tensor([265])
tensor([[ 42, 266,   2, 267,  85, 268, 269]]) tensor([270])
tensor([[ 42, 181,   2,  63,  39, 182, 183, 149, 184, 185]]) tensor([186])
tensor([[ 10, 146,   3, 147, 178,   5,   3,  72, 179]]) tensor([180])
tensor([[  1,   2,   3,  37,  38,  39, 168]]) tensor([169])
tensor([[ 42,  18,   2,   3, 293, 149,   3, 294]]) tensor([212])
tensor([[  1,   2,   3,  33,  34,   5, 256]]) tensor([257])
tensor([[ 42, 142,   2, 143,  39, 182, 280]]) tensor([281])
tensor([[ 42, 302, 303, 121, 304, 165, 305, 306]]) tensor([307])
tensor([[42, 18,  2, 63, 64,  3, 65, 66]]) tensor([67])
tensor([[ 42, 129,   2,  63,  64,   3, 130, 131]]) tensor([132])
tensor([[  1,   2,   3,   4,   5, 247, 248]]) tensor([249])
tensor([[10, 56,  3, 57,  5, 58]]) tensor([59])
tensor([[  1,   2,   3, 147, 120,  85,   3, 289, 290]]) tensor([125])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 10,   2,  63,  64,   3, 295,   5, 296]]) tensor([297])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[  1,   2,   3,   4,   5, 112]]) tensor([329])
tensor([[ 42, 174,   2,   3,  17, 175, 176]]) tensor([177])
tensor([[  1,   2,   3, 220,   5,  14, 221, 222]]) tensor([223])
tensor([[  1,   2,   3,  71,   5, 162]]) tensor([163])
tensor([[  1,   2,   3, 153,  88,  19, 199, 200]]) tensor([201])
tensor([[  1,   2,   3,   4,   5, 298]]) tensor([299])
tensor([[  1,   2,   3,   4,   5, 116]]) tensor([117])
tensor([[ 80,  81, 133,  83,  19,   3,  21,  22]]) tensor([36])
tensor([[  1,   2,   3, 244,   5, 245]]) tensor([246])
tensor([[ 42, 330,   2,  63,  64,   3, 331,   5, 332]]) tensor([333])
tensor([[  1,   2,   3, 106,   5, 107,  19, 108]]) tensor([109])
tensor([[  1,   2,   3, 170, 171, 172,  85,  86]]) tensor([173])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[ 42, 142,   2, 235, 149,   3, 236, 237]]) tensor([238])
tensor([[ 1,  2,  3, 94, 95, 96]]) tensor([97])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[ 10,  77, 215]]) tensor([216])
tensor([[ 10,  77, 114]]) tensor([115])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[80, 81, 82, 83, 84, 85, 86]]) tensor([87])
tensor([[ 1,  2,  3, 71,  5,  3, 72, 73]]) tensor([74])
tensor([[  1,  89, 239, 240, 241, 242]]) tensor([243])
tensor([[ 1,  2,  3, 60, 25,  5, 26, 19, 61]]) tensor([62])
tensor([[ 42, 324,   2, 325,  63,  64,   3, 326, 327]]) tensor([328])
tensor([[ 80,  81, 202,  83,  19,   3, 203, 204, 205]]) tensor([206])
tensor([[ 42,   2,   3, 286, 218, 287]]) tensor([288])
tensor([[ 42, 142,   2, 143,  39, 144]]) tensor([145])
tensor([[ 10,  11, 164, 165, 166]]) tensor([167])
tensor([[  1,   2,   3,  94, 142,  19,   3,  52]]) tensor([192])
tensor([[ 10, 146,   3, 147, 282,  95, 283,   5,   3, 284]]) tensor([285])
tensor([[ 10,  11, 196, 165, 197]]) tensor([198])
tensor([[10, 77, 78]]) tensor([79])
tensor([[10,  2,  3, 68,  5, 69]]) tensor([70])
tensor([[ 10, 320,   3, 321, 322]]) tensor([323])
tensor([[  1,   2,   3,   4,   5, 213]]) tensor([214])
tensor([[ 42, 311, 312, 121,  14, 313, 314, 165, 315, 316, 317, 318]]) tensor([319])
tensor([[  1,   2,   3, 153, 154,  19, 155]]) tensor([156])
tensor([[  1,   2,   3,   4,   5, 101]]) tensor([102])
tensor([[42, 88, 89, 90, 91, 39, 92]]) tensor([93])
tensor([[ 10,  98,   3, 107, 250]]) tensor([251])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 52]]) tensor([53])
tensor([[ 1,  2,  3,  4,  5, 75]]) tensor([76])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[ 1,  2,  3, 71,  5, 54]]) tensor([271])
tensor([[ 42,  18, 121,   3, 193, 194]]) tensor([195])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 42,   2,   3, 217, 142, 175, 218, 176]]) tensor([219])
tensor([[ 42, 207,   2,  14, 208, 209, 210, 211]]) tensor([212])
tensor([[  1,   2,   3, 230,   5, 231, 232, 233]]) tensor([234])
tensor([[10, 98,  3, 99]]) tensor([100])
tensor([[  1,   2,   3, 187, 188, 189, 190]]) tensor([191])
tensor([[  1,   2,   3,   4,   5, 291]]) tensor([292])
tensor([[ 42, 142, 121,   3, 258,   5, 259]]) tensor([260])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[ 80,  81, 157, 158,  14, 159, 160]]) tensor([161])
tensor([[ 42, 142,   2,  63,  39,   3, 334, 335]]) tensor([336])
tensor([[ 80,  81, 272, 158,  14, 273, 160]]) tensor([36])
tensor([[ 1,  2,  3,  4,  5, 54]]) tensor([55])
tensor([[ 42, 120, 121,   3, 122, 123, 124]]) tensor([125])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[ 10,  77,   3, 308,  19, 309]]) tensor([310])
tensor([[  1,   2,   3,   4,   5, 140]]) tensor([141])
tensor([[ 80,  81, 300,  83,  19,  14, 301]]) tensor([87])
tensor([[ 42,  88,  89, 252, 253,  19,  39, 254]]) tensor([255])
tensor([[ 42, 274, 275,  14, 276, 277, 165, 278]]) tensor([279])
tensor([[ 42, 103,   2,   3, 104]]) tensor([105])
tensor([[  1,   2,   3,  37, 137,   5, 138]]) tensor([139])
tensor([[ 42, 110,   2, 111,  19, 112]]) tensor([113])
tensor([[  1,   2,   3, 126, 127,  19,   3,  52]]) tensor([128])
tensor([[ 10,  29, 134, 135]]) tensor([136])
tensor([[ 10, 146,   3, 147, 148, 149, 150,  85,   3, 151]]) tensor([152])

In [68]:
import torch.nn as nn

In [124]:
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    print(final.shape)
    output = self.fc(final[-1])
    return output

In [101]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [116]:
learning_rate = 0.001
epoch = 20

In [117]:
mmodel = SimpleRNN(len(vocab))

In [118]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(mmodel.parameters(), lr=learning_rate)

In [119]:
# training loop

for epoch_idx in range(epoch):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = mmodel(question)

    # Ensure prediction is [batch_size, vocab_size] and target is [batch_size]
    loss = criterion(output.view(-1, len(vocab)), answer.view(-1))

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch_idx+1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 528.6530
Epoch: 2, Loss: 462.0636
Epoch: 3, Loss: 383.3344
Epoch: 4, Loss: 320.0419
Epoch: 5, Loss: 268.4808
Epoch: 6, Loss: 221.2540
Epoch: 7, Loss: 178.5389
Epoch: 8, Loss: 139.4572
Epoch: 9, Loss: 107.0973
Epoch: 10, Loss: 82.0228
Epoch: 11, Loss: 62.9876
Epoch: 12, Loss: 48.9226
Epoch: 13, Loss: 38.4225
Epoch: 14, Loss: 30.9268
Epoch: 15, Loss: 25.5563
Epoch: 16, Loss: 21.0516
Epoch: 17, Loss: 17.6763
Epoch: 18, Loss: 15.0424
Epoch: 19, Loss: 13.1202
Epoch: 20, Loss: 11.4160

In [120]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [122]:
predict(mmodel, "What is the largest planet in our solar system?")

jupiter

In [123]:
list(vocab.keys())[7]

'paris'